apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      env: production
  template:
    metadata:
      name: my-pod
      labels:
        env: production
    spec:
      containers:
      - name: my-con
        image: krushnakant241/webos:v1
